### ISSUE TITLE
No new logfile get written

### ISSUE THREAD

**Issue by shaas** [i-am-offline/smarthome.plugin.autoblind#21]
AutoBlind only generates logfiles for each item once at startup instead of every day.

This is my plugin configuration:

```
autoblind:
    class_name: AutoBlind
    class_path: plugins.autoblind
    log_level: 1 
    log_maxage: 5
```

The only logging in regarding AutoBlind in the smarthome.log are the following two lines every day:
```
2018-02-24  00:30:00 INFO     plugins.autoblind.AutoBlind: Remove old logfiles Removing logfiles older than 5 days
2018-02-24  00:30:00 INFO     plugins.autoblind.AutoBlind: Remove old logfiles 0 files removed, 0 errors occured
```
